[package]
name = "noeio-proto"
version = "0.1.0"
edition = "2024"

[features]
default = []
noeio = []
noeio-derper = []

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
protoc-bin-vendored = { workspace = true }
